### ISSUE TITLE
Installation Testing

### ISSUE THREAD

**Issue by alykhalifa** [researchapps/polysolver#2]
Thanks a lot for the tool.
I installed singualrity and polysolver on windows machine using vagrant, virtualbox and git.
The installation went smooth, with no errors.
For the first run, some dependencies appear missing by pointing to files not available at "/home/polysolver" as the folder itself wasn't present, so I created a link to the /usr/local/libexic/polysolver" and it ran well with some warninging like the following:
`perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").`

Currently, I trying to test that it works as expected, so I followed the instructions within the "Testing" section "3.1 Polysolver". 
After running the "shell_call_hla_type" script againt "/home/polysolver/test/test.bam" and by comparing the resultant file "winners.hla.nofreq.txt" to "/home/polysolver/test/orig.winners.hla.txt", some differences appears as follow:

`diff test/winners.hla.nofreq.txt /home/polysolver/test/orig.winners.hla.txt
1,3c1,3
< -e HLA-A      -e hla_a_01_01_01_01    -e hla_a_01_01_01_01
< HLA-B -e hla_b_07_02_01       -e hla_b_07_02_01
< HLA-C -e hla_c_01_02_01       -e hla_c_01_02_01
---
> HLA-A hla_a_24_02_01_01       hla_a_24_02_01_01
> HLA-B hla_b_39_01_01_02l      hla_b_39_01_01_02l
> HLA-C hla_c_07_01_05  hla_c_06_02_01_01
`

What I may do to confirm that this was a correct installation?

Thanks,

**Comment by vsoch** [comment]
hey @alykhalifa ! I'm not familiar with this domain so I'm not sure, but a first test would be to run and compare against the original docker image:

- https://hub.docker.com/r/sachet/polysolver/

and then to contact the creator of the software (sachet on Docker Hub) and find the original repo.

**Comment by alykhalifa** [comment]
Thanks a lot @vsoch ,
I'll try to contact sachet.

**Comment by vsoch** [comment]
If this is the same thing, this might be a good place to start, or at least find contacts:

http://archive.broadinstitute.org/cancer/cga/polysolver_run

**Comment by alykhalifa** [comment]
Thanks Vanessa.
I've just posted the same issue as a comment on https://hub.docker.com/r/sachet/polysolver/.
Unfortunately, I couldn't find contacts wihtin the CGA webpage, so I'll wait for a while and then I may contact some one from the CGA.

**Comment by alykhalifa** [comment]
Hi Vanessa,
I tried the docker image and it was needing at least 4g as RAM in order to work. Thanks for Sachet.
However, when I tried singularity of the same docker image version, it still gives unaligned test results, even on +4g RAM machines.
Did you try running testing on the singularity image? did you get the aligned test results (i.e. result file is the same as the orig.winners.hla.txt)?
I checked Gregory's comment on "[Limit cpus and memory in Singularity](https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/5byecITBQuw)", so may be nothing can be done for limiting or specifying RAM allocation for singularity except running over a +4g RAM machine?
Any advice?
Thanks again Vanessa for offering it as a singularity container.
Aly

**Comment by vsoch** [comment]
hey @alykhalifa - I'm not a trained biologist, so I don't typically do these kinds of analyses, I didn't do tests to confirm they are equivalent. I would guess that the difference has to do with differences with regard to use of memory (as you highlighted) but I don't have knowledge/advice beyond that.

**Comment by alykhalifa** [comment]
Thanks @vsoch .
