### ISSUE TITLE
what does n1=? and n2=? mean in the log file

### ISSUE THREAD

**Issue by cjieming** [researchapps/polysolver#4]
Hi I ran Polysolver and I got n1=7800 and n2=7800 in the log file. May I know what these numbers mean? Thanks!

**Comment by vsoch** [comment]
hey @cjieming ! I can't give much insight to the tool itself, but I can point you to this comment issue to start your investigation:

https://github.com/researchapps/polysolver/issues/2#issuecomment-325225922

The tool was created from a Docker image that was originally developed by a group at Harvard, so browsing their site and reaching out to them would be a good start to understand the output.

**Comment by cjieming** [comment]
I see, their site doesnt seem to be updated. I will try to contact the authors. Thanks!
